### ISSUE TITLE
Make Bjorklund mode work

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#205]
Like, make the sliders actually do a thing

**Comment by mearabai** [comment]
FYI, the "ugly" side of the distribution slider isn't currently working out of the gate. When you add onsets, they are partially distributed, even when the slider is all the way to the left (in ugly mode). If you move the ugliness slider to the right and then back again it clumps them together as it should, but it's currently impossible to add onsets and have them start out clumped so you can then step through the algorithm. I'm thinking this is a good thing to demo for ignite, do you think this could get fixed by early Monday? Danke!

**Comment by starakaj** [comment]
Tiny error: a < was actually supposed to be a >. It happens, try it now.

**Comment by mearabai** [comment]
Looking good.
