### ISSUE TITLE
Undo should include necklaces that have been duplicated via dragging.

### ISSUE THREAD

**Issue by mearabai** [starakaj/rnecklace#286]
Right now if you drag a necklace to duplicate it on another dock you can't undo that.

**Comment by starakaj** [comment]
This is super true

**Comment by starakaj** [comment]
So I think I see what you mean. When you undo a copy, you expect to do it from the necklace _from_ which you copied, rather than from the necklace _to_ which you copied. Right now, if you copy from A to B, switch to B and then press undo, it works. Which is actually what I would expect. Since the "copy" affects necklace B, not A, it makes sense (at least in my possibly deviant mind) that you should undo from necklace B. 

You could make the case that you should undo from A, since you're looking at A when you copy from A to B. But consider this: what should happen if you switch to B and press undo. Nothing? That doesn't make much sense; something surely has changed for B. You could argue that you should be able to undo the copy from A _or_ B, but I don't think that's right either because surely the change can't be on _both_ A and B's undo stacks.

Maybe there's a third way: when copying from A to B, we switch to viewing B. Does that sound like it would make things less confusing?

**Comment by mearabai** [comment]
Yes, I like that final idea a lot--it clarifies the whole stack thing you're talking about, which the consumer does not need to be muddled by. Word!

**Comment by starakaj** [comment]
Cool, it is done.
