### ISSUE TITLE
First time mode

### ISSUE THREAD

**Issue by starakaj** [starakaj/rnecklace#342]

**Comment by starakaj** [comment]
Okay, Quick Start is now in the config menu. Check it out.

**Comment by mearabai** [comment]
Looking good! I think we can tweak the text a bit, and I think the lines should be white, not teal.
Rather than saying quick start, maybe we should say "tap" or something? Otherwise it just feels like it could be taking a long time to load.

Perhaps something like:

Step one: A vertical swipe here changes pulse count/ Drag up and down here to change pulse count
Step two: Start rotating your rhythm by touching down here
Step three: ya ya is goot
Step four: ""

Maybe we can edit this together, might be faster.

**Comment by starakaj** [comment]
Yeah, let's look at it when you get in as part of our exfoliation.

**Comment by starakaj** [comment]
Less gross, huh?

**Comment by mearabai** [comment]
Looking great.  It should be noted that if quick start is selected while Bjorklund is open the highlighting squares don't line up with what they are trying to draw attention to. Maybe selecting quickstart should close Bjorklund? I'll make a ticket.
